## Importing library

In [2]:
import pandas as pd

In [3]:
file = "DataSet1.csv"
file

'DataSet1.csv'

## Loading the Dataset

In [4]:
df = pd.read_csv(file)
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,26-07-2024,02:00:00 PM,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,25-07-2024,10:20:00 PM,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,30-07-2024,07:59:00 PM,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,22-07-2024,03:15:00 AM,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,02-07-2024,09:02:00 AM,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,31-07-2024,09:06:00 AM,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,31-07-2024,03:12:00 PM,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,31-07-2024,01:59:00 PM,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,31-07-2024,02:56:00 PM,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,31-07-2024,01:57:00 PM,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

## Step 1: Understand the Data

In [5]:
# Top rows

df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,26-07-2024,02:00:00 PM,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,25-07-2024,10:20:00 PM,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,30-07-2024,07:59:00 PM,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,22-07-2024,03:15:00 AM,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,02-07-2024,09:02:00 AM,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [6]:
# Checking dataset info (columns, data types, missing values)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  object
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: float64(4), int64(2), object(14)
memory usage: 15.7+ MB

In [7]:
# Summary statistics for numeric columns

df.describe()

,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000
mean,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313
std,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957
min,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000
25%,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000
50%,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000
75%,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000
max,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000

In [8]:
# Checking  missing values

df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

In [9]:
# checking data type

df.dtypes

Date                           object
Time                           object
Booking_ID                     object
Booking_Status                 object
Customer_ID                    object
Vehicle_Type                   object
Pickup_Location                object
Drop_Location                  object
V_TAT                         float64
C_TAT                         float64
Canceled_Rides_by_Customer     object
Canceled_Rides_by_Driver       object
Incomplete_Rides               object
Incomplete_Rides_Reason        object
Booking_Value                   int64
Payment_Method                 object
Ride_Distance                   int64
Driver_Ratings                float64
Customer_Rating               float64
Vehicle Images                 object
dtype: object

## Step 2: Data Cleaning & Preprocessing

In [10]:
#  Convert Date column

df['Date'] = pd.to_datetime(df['Date'])

C:\Users\Shrey\AppData\Local\Temp\ipykernel_23944\2051680660.py:3: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'])

In [11]:
df['Date']

0        2024-07-26
1        2024-07-25
2        2024-07-30
3        2024-07-22
4        2024-07-02
            ...
103019   2024-07-31
103020   2024-07-31
103021   2024-07-31
103022   2024-07-31
103023   2024-07-31
Name: Date, Length: 103024, dtype: datetime64[ns]

In [12]:
# Check for duplicates

df.duplicated().sum()

np.int64(0)

In [13]:
# Convert Time column to datetime
df['Time'] = pd.to_datetime(df['Time'], format='mixed').dt.time

In [14]:
df['Time']

0         14:00:00
1         22:20:00
2         19:59:00
3         03:15:00
4         09:02:00
            ...
103019    09:06:00
103020    15:12:00
103021    13:59:00
103022    14:56:00
103023    13:57:00
Name: Time, Length: 103024, dtype: object

In [15]:
df['Hour'] = df['Time'].apply(lambda x: x.hour)
df['Hour']

0         14
1         22
2         19
3          3
4          9
          ..
103019     9
103020    15
103021    13
103022    14
103023    13
Name: Hour, Length: 103024, dtype: int64

In [16]:
# Creating a new column 'DayOfWeek' from the 'Date' column

df['DayOfWeek'] = df['Date'].dt.day_name()

# Check the first 5 rows
df[['Date', 'DayOfWeek']].head()

        Date DayOfWeek
0 2024-07-26    Friday
1 2024-07-25  Thursday
2 2024-07-30   Tuesday
3 2024-07-22    Monday
4 2024-07-02   Tuesday

### Feature Engineering / Derived Columns

In [17]:
# Creating a new column 'Month' from the 'Date' column

df['Month'] = df['Date'].dt.month

# Check the first 5 rows
df[['Date', 'Month']].head()

        Date  Month
0 2024-07-26      7
1 2024-07-25      7
2 2024-07-30      7
3 2024-07-22      7
4 2024-07-02      7

In [18]:
### Completion ###

# Create IsCompleted column: 1 if ride was successful, 0 otherwise
df['IsCompleted'] = df['Booking_Status'].apply(lambda x: 1 if x == 'Success' else 0)

# Check first 5 rows
df[['Booking_Status', 'IsCompleted']].head()

         Booking_Status  IsCompleted
0    Canceled by Driver            0
1               Success            1
2               Success            1
3  Canceled by Customer            0
4               Success            1

In [19]:
### Cancellation Type (Customer vs Driver) ###


# Create a new column 'Cancellation_Type'
def get_cancellation_type(row):
    if row['Booking_Status'] == 'Canceled by Customer':
        return 'Customer'
    elif row['Booking_Status'] == 'Canceled by Driver':
        return 'Driver'
    else:
        return 'Success'

df['Cancellation_Type'] = df.apply(get_cancellation_type, axis=1)

# Check first 5 rows
df[['Booking_Status', 'Cancellation_Type']].head()

         Booking_Status Cancellation_Type
0    Canceled by Driver            Driver
1               Success           Success
2               Success           Success
3  Canceled by Customer          Customer
4               Success           Success

# Replacing nulls with replacement on Categorical Columns

In [20]:
# Verify columns exist

df[
    [
        'Canceled_Rides_by_Customer',
        'Canceled_Rides_by_Driver',
        'Incomplete_Rides_Reason',
        'Payment_Method'
    ]
].isnull().sum()

Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides_Reason       99098
Payment_Method                39057
dtype: int64

In [21]:
# Replace NULLs

df['Canceled_Rides_by_Customer'] = df['Canceled_Rides_by_Customer'].fillna('Not Cancelled')

df['Canceled_Rides_by_Driver'] = df['Canceled_Rides_by_Driver'].fillna('Not Cancelled')

df['Incomplete_Rides_Reason'] = df['Incomplete_Rides_Reason'].fillna('No Failure')

df['Payment_Method'] = df['Payment_Method'].fillna('No Transaction')

In [22]:
# Verify replacements

df[
    [
        'Canceled_Rides_by_Customer',
        'Canceled_Rides_by_Driver',
        'Incomplete_Rides_Reason',
        'Payment_Method'
    ]
].isnull().sum()

Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides_Reason       0
Payment_Method                0
dtype: int64

In [23]:
# Quick visual confirmation

df[
    [
        'Booking_Status',
        'Canceled_Rides_by_Customer',
        'Canceled_Rides_by_Driver',
        'Incomplete_Rides_Reason',
        'Payment_Method'
    ]
].head(10)

,Booking_Status,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides_Reason,Payment_Method
0,Canceled by Driver,Not Cancelled,Personal & Car related issue,No Failure,No Transaction
1,Success,Not Cancelled,Not Cancelled,No Failure,Cash
2,Success,Not Cancelled,Not Cancelled,No Failure,UPI
3,Canceled by Customer,Driver is not moving towards pickup location,Not Cancelled,No Failure,No Transaction
4,Success,Not Cancelled,Not Cancelled,No Failure,Credit Card
5,Success,Not Cancelled,Not Cancelled,No Failure,UPI
6,Success,Not Cancelled,Not Cancelled,No Failure,Cash
7,Canceled by Driver,Not Cancelled,Personal & Car related issue,No Failure,No Transaction
8,Driver Not Found,Not Cancelled,Not Cancelled,No Failure,No Transaction
9,Canceled by Driver,Not Cancelled,Personal & Car related issue,No Failure,No Transaction

In [30]:
df['Incomplete_Rides'] = df['Incomplete_Rides'].fillna('Not Applicable')
df['Incomplete_Rides']

0         Not Applicable
1                     No
2                     No
3         Not Applicable
4                     No
               ...
103019                No
103020                No
103021                No
103022                No
103023                No
Name: Incomplete_Rides, Length: 103024, dtype: object

# Replacing nulls with replacement on Categorical Columns

In [31]:
df.to_csv('OLA_Ride_Cleaned_file.csv', index=False)

In [32]:
df = pd.read_csv('OLA_Ride_Cleaned_file.csv')
df.head(10)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,Hour,DayOfWeek,Month,IsCompleted,Cancellation_Type
0,2024-07-26,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,...,No Transaction,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...,14,Friday,7,0,Driver
1,2024-07-25,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,...,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...,22,Thursday,7,1,Success
2,2024-07-30,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,...,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...,19,Tuesday,7,1,Success
3,2024-07-22,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,...,No Transaction,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...,3,Monday,7,0,Customer
4,2024-07-02,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,...,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...,9,Tuesday,7,1,Success
5,2024-07-13,04:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,...,UPI,41,3.4,4.6,https://cdn-icons-png.flaticon.com/128/3202/32...,4,Saturday,7,1,Success
6,2024-07-23,09:51:00,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,...,Cash,49,3.2,4.5,https://cdn-icons-png.flaticon.com/128/9983/99...,9,Tuesday,7,1,Success
7,2024-07-11,11:12:00,CNR5374902489,Canceled by Driver,CID735691,Prime Plus,Bannerghatta Road,Sarjapur Road,NaN,NaN,...,No Transaction,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/11409/1...,11,Thursday,7,0,Driver
8,2024-07-01,19:19:00,CNR5030602354,Driver Not Found,CID999840,Mini,Chamarajpet,Peenya,NaN,NaN,...,No Transaction,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/3202/32...,19,Monday,7,0,Success
9,2024-07-18,01:31:00,CNR6328453219,Canceled by Driver,CID907133,Auto,RT Nagar,Varthur,NaN,NaN,...,No Transaction,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/16526/1...,1,Thursday,7,0,Driver